### ISSUE TITLE
Core as a NPM Module with bin script for managing ManiaJS.

### ISSUE THREAD

**Issue by tomvlk** [ManiaJS/ManiaJS#10]
A good move would be to move the core to a NPM module itself too, this will help updating the core once it's installed on a server.

With the core itself being a npm module, and having a 'start' project with just the core and plugins as dependencies in package.json you would be able to have the npm run as a update utility.

Only problems would be, the dependency of plugins to the core, when this will be a different version.
Solution could be, dependency injection in the plugin boot sequence, but it isn't nice.

Need to look for better solution, please reply if you have one.

Examples using this structure: https://github.com/pimatic/pimatic

**Comment by MiniGod** [comment]
I didn't look very much at that pimatic (tldr).

It could be cool if maniajs had a `bin` so you could install it globally with npm, and run it from anywhere? Event the same directory as the dedicated server, if one would like to?
- `maniajs init` would initialize some config file (similar to `npm init` or `git init`).
- `maniajs install dedimania` to install a plugin (would probably use `npm install` internally).
- `maniajs start` to start maniajs with the current config.

It would hide the source code from the user, which would be very nice (and a lot of other pros).

I'm just thinking out loud.

**Comment by tomvlk** [comment]
Was thinking of that too, the init would make the structure, start scripts (maybe), package.json with core in it (so it could be easely updated) and the plugin stuff + config.

**Comment by MiniGod** [comment]
It would be nice to semi-hide that from the user since you are mentioning a few files there. Maybe put it in a folder?
Or at least not bloat the working directory (like `git init` only creates the `.git` folder).

**Comment by tomvlk** [comment]
Well the init cmd will just create it in current folder right?
Add package.json with the core and main plugins as dependencies, run npm install and init config right?

**Comment by tomvlk** [comment]
Will be done with the CLI project.
