### ISSUE TITLE
Core does not run on case-sensitive systems

### ISSUE THREAD

**Issue by TheMaximum** [ManiaJS/ManiaJS#112]
- [ ] Server/callbacks/ManiaplanetCallbacks.ts --> Server/callbacks/ManiaPlanetCallbacks.ts
- [ ] Server/callbacks/TrackmaniaCallbacks.ts --> Server/callbacks/TrackManiaCallbacks.ts
- [ ] Util/configuration.ts --> Util/Configuration.ts
- [ ] Util/directory.ts --> Util/Directory.ts
- [ ] Change Database/Client.ts to use ../App instead of ../app
- [ ] Change Database/index.ts to use ../Util/Facade instead of ../Util/facade
- [ ] **Check all directories and files to use a capital letter!**

**Comment by MiniGod** [comment]
I am strongly against using capital letters in the filenames!

**Comment by tomvlk** [comment]
Also for typescript, where most files contains classes with names that have capital letters?

**Comment by MiniGod** [comment]
Yes.

**Comment by tomvlk** [comment]
K. 
@TheMaximum your opinion about it? :P Move to lowercase?

**Comment by TheMaximum** [comment]
Well, it was mostly about making sure everything works fine on case-senstive systems. So if you rather have it lowercase, then that is a solution as well. I'm personally happier with `ManiaPlanetCallbacks.ts` than `maniaplanetcallbacks.ts`, but I guess that's my personal taste (so: rather with capital than without, but I'm not an expert)...

**Comment by tomvlk** [comment]
I'm also happier with the capital letters for the filename. Especially with TypeScript, where classes are more like OO classes.
