### ISSUE TITLE
SettingManager should support player-dependent settings

### ISSUE THREAD

**Issue by TheMaximum** [ManiaJS/ManiaJS#115]
In order for plugins to store player related settings (in the current case the setting for the CP difference display), it'll have to make a combined setting key, f.e. "cpdifference-1" (player id) or "cpdifference-them" (player login). In my eyes this creates an unwanted scenario where you in effect have a different setting for each player. It should be possible to have one setting key with different values for different players.

Any ideas/remarks on this?

**Comment by tomvlk** [comment]
Adding column to the settings table that is optional (null) would be the best option. Specially for performance reasons.

To implement this in the SettingManager, it would be nice to pass the **`key` parameter as an array**, where you give the normal string key, and any integer id, or maybe even a string as second.

Maybe better to make it _generic_, and not call it `playerid`, but `foreignkey` or something. So this mapping could also be used for other things.

Also it could be possible to make the key array dynamically in length, so you could add keys like an array, and on the  background it's handling the 'dirty' stuff for you.

At least we need to really overthink this **Settings** component.
