### ISSUE TITLE
Convert to ES6, drop support node v4.

### ISSUE THREAD

**Issue by tomvlk** [ManiaJS/ManiaJS#2]

**Comment by TheMaximum** [comment]
Does this mean that we can/want to use things like classes (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)?

**Comment by tomvlk** [comment]
"JavaScript classes are introduced in ECMAScript 6 and are syntactical sugar over JavaScript's existing prototype-based inheritance"

ES6 === ECMAScript 6
So we need to support it and convert to classes.

**Comment by TheMaximum** [comment]
I was aware of ES6 == ECMAScript 6. I was just wondering if we'd like to use that feature, which makes the whole thing more understandable for a (Node.)JS noob like me :stuck_out_tongue:

**Comment by tomvlk** [comment]
Ye we will.
