### ISSUE TITLE
Transpile build instead of using register hook

### ISSUE THREAD

**Issue by tomvlk** [ManiaJS/ManiaJS#51]
Currently, transpiling at runtime is costy.
Memory footprint is 200mb when fully started, spikes to 500mb when starting for the first time.

We need to use babel cli at npm start for transpiling. Also transpiling modules that are es6 (like all our plugins are).
Or.. have the modules transpile at their own before publishing..

**Comment by tomvlk** [comment]
Another option would be using gulp/grunt and transpile only the node_modules/\* that are plugins (by checking config at gulp) and the main /src into /build via babel-cli.

**Comment by tomvlk** [comment]
@MiniGod

**Comment by tomvlk** [comment]
Or let the plugins have a prepublish compile so the one on NPM will be transpiled, source will be es6 + uml import/export.

Think that would be the best.

```
"scripts": {
    "compile": "babel src/ -d lib/",
    "prepublish": "npm run compile"
}
```

in the package.json and:

```
# .gitignore
lib
# .npmignore
src/
```

in the gitignore and npmignore

For development it would be great to still have the babel-require hook. This will result in using modules without transpiliing (so you could link local plugins).

**Comment by MiniGod** [comment]
Should definitely go for that last solution!
