### ISSUE TITLE
Separate UI from logic?

### ISSUE THREAD

**Issue by MiniGod** [ManiaJS/ManiaJS#57]
I got an idea. Please discuss. It would be nice if plugins only did the logic, then we could have UI "plugins" which could be switched out.
Think of for instance a cp-times plugin. The only thing it would do is to wait for checkpoint events and expose an array of checkpoints and their best times.
Then you have a completely separate plugin (view?) which uses the data from the plugin, and displays it to the player. The view would depend on the plugin, and it could be switched with some other cp-times view.

I just realized I while typing it that it's almost like a MVVM. We have the Models (player, map, etc), Views (cp-times manialink something), and the ViewModel (the cp-times plugin).

You could have plugins without views even? Saving stuff to the database and only outputting to the chat? Or should chat maybe be part of the view?
# abstractallthethings
# overthinking

**Comment by tomvlk** [comment]
Great idea.
Really think that the separate plugin is a good idea, but it could be in the plugin too (the view) and have it separate from the logic. 

But think also of it, the plugin developers (community, not us) need to adapt it too, so need to be logical and simple to do I think.

Currently every plugin (the class extending Plugin (interface)) is also an eventemitter. And with that you could trigger ui updates ;)
