### ISSUE TITLE
Adding database structure, (sequelize).

### ISSUE THREAD

**Issue by TheMaximum** [ManiaJS/ManiaJS#6]
You might be prefering other database systems at the moment, but I think we should also look at what is currently being used in the community and make sure our solution is very easy to change over to, without the hassle of creating new database serverinstances.

Also: there are enough teams/sites which include information from the servers via those MySQL databases. If we don't support MySQL, lots of people will already stay at (X)Aseco.
_Saying that, we'd also have to look at either using the XAseco database structure, or provide some tool to convert it..._

**Comment by tomvlk** [comment]
I can see two different database options so far. 
Relational database and NoSQL database. 

In combination with the plugins architecture and js architecture itself (objects) it's way more easy to suppor NoSQL. Especially when we want to easily upgrade ManiaJS and the plugins. 

In other hands. Indeed it's a extra requirement for the systems (assuming most of the current servers have MySQL already in place). But I can only see that as a positive point to use relational databases. Downsides are. Migrations, mapping, strict scheme. 

So I really think it's better to use a NoSQL based database. I know it's not good for the promotional view of the controller. But it is for the stable and long term base.

**Comment by TheMaximum** [comment]
I can understand your points regarding the drawbacks. But the "long term base" won't be there if you can't get servers/users towards your controller. If the change it too great, which switching away from MySQL is for the most people, the switch won't be made and people stay at the same old thing...

If MySQL is not used for the controller, in my example (Smurfen), I'd have to completely rewrite website/SmurfsCup site/working of plugins. Let alone that we might not be able to carry over the data we have collected so far. This will certainly lead to a no-no for moving away from XAseco to ManiaJS...

**Comment by tomvlk** [comment]
We could make a api plugin that provide the data to an api for example. API's are really fast made in node :smiley:

**Comment by TheMaximum** [comment]
I will be happy with whatever solution we can create. Either with an extra layer that makes it possible to use MySQL, NoSQL, SQLite, or whatever other solution.

I hope you understand that I'm also looking at this from a Smurf-perspective. I really want to switch to something more durable than the current XAseco (which hasn't been updated lately and doesn't support PHP7 - due to mysql_-issues). When MySQL isn't supported, it will be hard to make the switch... :cry:

**Comment by tomvlk** [comment]
Another option is to use Sequelize (what is in the current pre-prototype version). This supports multiple database dialects and scheme definition, migration and relationship mapping.
http://sequelize.readthedocs.org/en/latest/

**Comment by tomvlk** [comment]
Output: Sequelize.
